const laptops = [
    {
        index:1,
        name:'MSI Core i5 11th..',
        source: require('./assets/laptop1.1.jpeg'),
        disPrice:50990,
        MRP: 67990,
        discount: "25%",
        delivery:'Get it by Tomorrow',
        images:[{source:require('./assets/laptop1.1.jpeg')}, {source:require('./assets/laptop1.2.jpeg')}, {source:require('./assets/laptop1.3.jpeg')}],
        highlights1:'Intel Core i5 11th Gen',
        highlights2:'8GB | 512GB',
        highlights3:'Windows 11',
        highlights4:'NVDIA GeForce GTX',

    },
    {
        index:2,
        name:'Lenovo IdeaPad..',
        source: require('./assets/laptop2.1.jpeg'),
        disPrice:47990,
        MRP: 70790,
        discount: "32%",
        delivery:'Get it in 2 days',
        images:[{source:require('./assets/laptop2.1.jpeg')}, {source:require('./assets/laptop2.2.jpeg')}, {source:require('./assets/laptop2.3.jpeg')}],
        highlights1:'AMD Ryzen 7 Octa Core',
        highlights2:'8GB | 256GB',
        highlights3:'Windows 11',
        highlights4:'AMD Radeon',
    },
    {
        index:3,
        name:'Acer Aspire 7(2..',
        source: require('./assets/laptop3.1.jpeg'),
        disPrice:52990,
        MRP: 82999,
        discount: "36%",
        delivery:'Get it by Tomorrow',
        images:[{source:require('./assets/laptop3.1.jpeg')}, {source:require('./assets/laptop3.2.jpeg')}, {source:require('./assets/laptop3.3.jpeg')}],
        highlights1:'Intel Core i5 9th Gen',
        highlights2:'16GB | 256GB',
        highlights3:'Windows 11',
        highlights4:'NVDIA GeForce GTX',
    },
    {
        index:4,
        name:'Asus TUF Gamin..',
        source: require('./assets/laptop4.1.jpeg'),
        disPrice:52433,
        MRP: 75990,
        discount: "31%",
        delivery:'Get it in 5 days',
        images:[{source:require('./assets/laptop4.1.jpeg')}, {source:require('./assets/laptop4.2.jpeg')}, {source:require('./assets/laptop4.3.jpeg')}],
        highlights1:'AMD Ryzen 5 Octa Core',
        highlights2:'16GB | 512GB',
        highlights3:'Windows 11',
        highlights4:'AMD Radeon',
    },
    {
        index:5,
        name:'HP Victus Core i..',
        source: require('./assets/laptop5.1.jpeg'),
        disPrice:62890,
        MRP: 74829,
        discount: "15%",
        delivery:'Get it by Tomorrow',
        images:[{source:require('./assets/laptop5.1.jpeg')}, {source:require('./assets/laptop5.2.jpeg')}, {source:require('./assets/laptop5.3.jpeg')}],
        highlights1:'Intel Core i7 11th Gen',
        highlights2:'8GB | 256GB',
        highlights3:'Windows 11',
        highlights4:'NVDIA GeForce GTX',
    },
]

export {laptops};
